"""
Pre-build script for PlatformIO.
Reads src/version.h, increments VERSION_BUILD by 1, and rewrites the file.
Run automatically before every build via:
    extra_scripts = pre:increment_version.py
"""

import os

Import("env")  # PlatformIO environment injection

VERSION_FILE = os.path.join(env.subst("$PROJECT_DIR"), "src", "version.h")

major = 1
minor = 1
build = 0

if os.path.exists(VERSION_FILE):
    with open(VERSION_FILE, "r") as f:
        for line in f:
            parts = line.split()
            if len(parts) == 3 and parts[0] == "#define":
                if parts[1] == "FIRMWARE_VERSION_MAJOR":
                    major = int(parts[2])
                elif parts[1] == "FIRMWARE_VERSION_MINOR":
                    minor = int(parts[2])
                elif parts[1] == "FIRMWARE_VERSION_BUILD":
                    build = int(parts[2])

build += 1

content = (
    "#pragma once\n"
    "// Auto-generated by increment_version.py — do not edit manually\n"
    "#define FIRMWARE_VERSION_MAJOR {major}\n"
    "#define FIRMWARE_VERSION_MINOR {minor}\n"
    "#define FIRMWARE_VERSION_BUILD {build}\n"
    '#define FIRMWARE_VERSION "{major}.{minor}.{build}"\n'
).format(major=major, minor=minor, build=build)

with open(VERSION_FILE, "w") as f:
    f.write(content)

print("Firmware version: {}.{}.{}".format(major, minor, build))
