#pragma once
// Auto-generated by increment_version.py — do not edit manually
#define FIRMWARE_VERSION_MAJOR 1
#define FIRMWARE_VERSION_MINOR 1
#define FIRMWARE_VERSION_BUILD 6
#define FIRMWARE_VERSION "1.1.6"
